### ISSUE TITLE
Can't save pastes on ctrlv.io

### ISSUE THREAD

**Issue by dshoreman** [ryanwinchester/ctrlv#10]
Clicking the Save button on https://ctrlv.io/new only produces a CORS policy error.

It would seem the production env is trying to talk to a test/dev environment on port 8888 that doesn't exist... Oops? :wink:

**Comment by dshoreman** [comment]
So the localhost/8888 thing could be from an extension. Still breaks if I change language, but not for the reasons I thought originally? I have no clue :D

**Comment by ryanwinchester** [comment]
Should be fixed now in #11
